### PR TITLE
Movecraft-Cannons

### PR DESCRIPTION
**Pull request by TylerS1066**
### Describe in detail what your pull request acomplishes
In the march to remove external dependencies and improve the code quality of Movecraft, the Cannons plugin integration is next up.  [Movecraft-Cannons](https://github.com/TylerS1066/Movecraft-Cannons) will someday house all the current movement of cannons, along with optional integration with Movecraft-Combat for damage tracking.

### Checklist
- [x] Proper internationalization
- [ ] Compiled/tested

### CODE REVIEW

**Comment by TylerS1066** [comment]
This has not been tested on 1.13+ yet, but there are no code additions (outside of those in the other two PRs).

**Comment by TylerS1066** [comment]
If somebody out there is using Cannons with Movecraft 1.13+, please head over to the [Movecraft-Cannons alpha release](https://github.com/TylerS1066/Movecraft-Cannons/releases/tag/v0.1.0) and test it out for me.

**Comment by TylerS1066** [comment]
@eirikh1996 ?

**Comment by ThishThinger** [comment]
I used the alpha release just then and it works fine most of time as the cannon can still be fired when moved (e.g. loaded, moved two blocks with Movecraft, fired).

However, there have been one or two times when I load the gunpowder and the projectile, move the airship, and attempt to fire, but the button that usually controls the cannon does not fire the cannon (the cannon still 'stores' the gunpowder and projectile, but there is no way to fire it). No more gunpowder/projectile can be loaded either, and the cannon has to be destroyed. Will attempt to replicate this issue.

**Comment by eirikh1996** [comment]
There are conflicts that need to be resolved

**Review by eirikh1996 — CHANGES_REQUESTED** [review]
There are conflicts that needs to be resolved

**Pull request closed without merging**
